---
# tasks file for enabling NAT and iptables persistence

- name: Install sysctl
  package:
    name: "{{ sysctl_package_names }}"

- name: Enable NAT sysctl value for IPv4 NAT
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    # sysctl_file: "/etc/sysctl.conf"

- name: Install packages for iptables persistence
  package:
    name: "{{ iptables_persistence_package_names }}"

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable service for iptables persistence
  service:
    name: "{{ iptables_persistence_service_name }}"
    enabled: yes
