---
# tasks file for openvpn

- name: Install OpenVPN
  package:
    name: openvpn
    state: present

- name: Install cURL
  package:
    name: curl
    state: present

- name: Install boto3
  package:
    name: python3-boto3
    state: present

- name: Copy OpenVPN config from files
  copy:
    src: cal.conf
    owner: root
    mode: 0600
    dest: /etc/openvpn/server/

- name: Install certificate fetch script
  copy:
    src: fetch_certs.sh
    owner: root
    mode: 0700
    dest: /etc/openvpn/server/

- name: Install common name verification script
  copy:
    src: verify-cn.py
    owner: root
    mode: 0700
    dest: /etc/openvpn/server/

- name: Copy OpenVPN crypto matter from SSM
  copy:
    content: "{{ lookup('aws_ssm', '/openvpn/server/{{ item }}') }}"
    owner: root
    mode: 0600
    dest: /etc/openvpn/server/{{ item }}
  with_items:
    - dh4096.pem
    - server.crt
    - server.key
    - ta.key

- name: Fetch DHS CA certificates using fetch_certs.sh
  command: /etc/openvpn/server/fetch_certs.sh
  args:
    chdir: /etc/openvpn/server
    creates: /etc/openvpn/server/certs

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable OpenVPN
  service:
    name: openvpn-server@cal
    enabled: yes
    state: started
