---
- name: Load var file based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml"
        - "{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install OpenVPN packages
  package:
    name: "{{ openvpn_package_names }}"

- name: Copy OpenVPN config from files
  copy:
    src: primary.conf
    owner: root
    mode: 0600
    dest: /etc/openvpn/server/

- name: Load tasks for installing common name verification script
  include: install_verify_cn.yml

- name: Install certificate fetch script
  copy:
    src: fetch_user_ca_certs.sh
    owner: root
    mode: 0700
    dest: /etc/openvpn/server/

- name: Fetch DHS CA certificates using fetch_user_ca_certs.sh
  command: /etc/openvpn/server/fetch_user_ca_certs.sh
  args:
    chdir: /etc/openvpn/server
    creates: /etc/openvpn/server/certs

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable OpenVPN
  service:
    name: "{{ openvpn_service_name }}@primary"
    enabled: yes
    state: stopped

- name: Configure OpenVPN service to run after multi-user and cloud-final
  lineinfile:
    dest: /lib/systemd/system/{{ openvpn_service_name }}@.service
    regexp: ^After=
    state: present
    line: After=network.target multi-user.target cloud-final.service

- name: Disable OpenVPN private tmp directory to allow certificate file sharing
  lineinfile:
    dest: /lib/systemd/system/{{ openvpn_service_name }}@.service
    regexp: ^PrivateTmp=
    state: present
    line: PrivateTmp=false

- name: Load tasks file for enabling NAT
  include: enable_nat.yml

- name: Configure ufw to allow OpenVPN via UDP
  ufw:
    comment: Allow OpenVPN via UDP
    proto: udp
    rule: allow
    to_port: openvpn
