---
# tasks file for openvpn

- name: Install OpenVPN
  package:
    name: openvpn
    state: present

- name: Install cURL
  package:
    name: curl
    state: present

- name: Install boto3
  pip:
    executable: pip3
    name:
      - boto3

- name: Copy OpenVPN config from files
  copy:
    src: primary.conf
    owner: root
    mode: 0600
    dest: /etc/openvpn/server/

- name: Install certificate fetch script
  copy:
    src: fetch_user_ca_certs.sh
    owner: root
    mode: 0700
    dest: /etc/openvpn/server/

- name: Install common name verification script
  copy:
    src: verify-cn.py
    owner: root
    mode: 0700
    dest: /etc/openvpn/server/

- name: Generate fresh Diffie-Hellman parameters (takes a while)
  command: openssl dhparam -out dh4096.pem 4096
  args:
    chdir: /etc/openvpn/server
    creates: /etc/openvpn/server/dh4096.pem

- name: Set Diffie-Hellman parameters permissions
  file:
    path: /etc/openvpn/server/dh4096.pem
    owner: root
    mode: 0600

- name: Fetch DHS CA certificates using fetch_user_ca_certs.sh
  command: /etc/openvpn/server/fetch_user_ca_certs.sh
  args:
    chdir: /etc/openvpn/server
    creates: /etc/openvpn/server/certs

# Unless you do this, systemd can sometimes get confused when you try
# to start a service you just installed
- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable OpenVPN
  service:
    name: openvpn-server@primary
    enabled: yes
    state: started
