---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: terraform/.terraform
platforms:
  - name: amazonlinux2
    image: amazonlinux:2
  - name: debian9
    image: debian:stretch-slim
  - name: debian10
    image: debian:buster-slim
  - name: debian11
    image: debian:bullseye-slim
  - name: kali
    image: kalilinux/kali-rolling
  - name: fedora29
    image: fedora:29
  # Ansible currently insists on installing python2-dnf, which does
  # not exist in Fedora 30.  Until that is resolved, we can't use
  # Fedora 30.
  # - name: fedora30
  #   image: fedora:30
  - name: fedora31
    image: fedora:31
  - name: ubuntu16
    image: ubuntu:xenial
  - name: ubuntu18
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
