---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    image: debian:stretch-slim
  - name: debian10
    image: debian:buster-slim
  - name: amazon2018.03
    image: amazonlinux:2018.03
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
